### ISSUE TITLE
Continuous Integration Set up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/visdom#782]
Please set up continuous integration and tests where possible using Github Actions or another service. Also add badges to the Readme file.

**Comment by mariobehling** [comment]
We are not assigning issues to external contributors. Please mention that you would like to work on the issue and make a pull request to resolve it shortly after. Thanks.

**Comment by iamareebjamal** [comment]
Can you please assign this issue to me?

**Comment by gyanprakash0221** [comment]
I would like to work on this issue @mariobehling

**Comment by dizcza** [comment]
Just came upon this issue. I do continuous integration with a remote visdom server involved. The solution is to set up a few environment flags in a CI of your choice (CircleCI, for example) and then opening a visdom client as following [(see the full code)](https://github.com/dizcza/pytorch-mighty/blob/7be3c1b883974cbb51258c7bb68375848b125fb2/mighty/monitor/viz.py#L37-L39):
```python
        port = int(os.environ.get('VISDOM_PORT', 8097))
        server = os.environ.get('VISDOM_SERVER', 'http://localhost')
        base_url = os.environ.get('VISDOM_BASE_URL', '/')
        viz = visdom.Visdom(..., server=server, port=port, base_url=base_url)
```
Assuming, of course, that you host a visdom server running elsewhere. The same web server could help to resolve this issue: https://github.com/fossasia/visdom/issues/607

Another attempt that I've not checked is to start a visdom server locally at each Travis/CircleCI build via a `screen` manager in the detached mode (`screen -S visdom -dm visdom`), and then communicate via the default visdom client in Python. The drawback of such appoarch is, of course, in case of a failure, you won't be able to look at the plots remotely because the session is closed when it dies.

The final, the simplest choice of tests setup is to run a visdom client in the offline mode. The drawback is obvious: the majority runs visdom servers in online mode; therefore, you will be covering the minority usage.
