### ISSUE TITLE
columnnames or xticklabels not work for line

### ISSUE THREAD

**Issue by hei6775** [fossasia/visdom#809]
Hello, I am newer in Visdom. I want to change the xticklabels. 
```
a = np.linspace(1,4,4)
vis.line(a,win="line plot", env="MyPlotEnv",
         opts=dict(
            columnnames = ['2012', '2013', '2014', '2015']
         ),
         )
```
If I change the `columnnames` to `xticklabels`, but nothing seems to have changed
But not work. What should I do?

**Comment by JackUrb** [comment]
I suspect in order to properly use `xticklabels`, you'll also need to provide `xtickvals`, but I'm not entirely sure. We [transform](https://github.com/fossasia/visdom/blob/e0a912d39f88e637f483c229c0fbf3d4da119ac5/py/visdom/__init__.py#L150-L166) incoming arguments to try to conform to the [plotly standard](https://plotly.com/javascript/tick-formatting/).

**Comment by hei6775** [comment]
Yes, you are right. After I tried to add `xtickvals`, it works!!
```
a = np.linspace(1,4,4)
b = np.linspace(0,3,4)
vis.line(X=b, Y=a,win="line plot3", env="MyPlotEnv",
         opts=dict(
            xtickmin=0,
            xtickmax=5,
            xtickstep=1,
            xtickvals=[1,2,3],
            xticklabels= ['2012','2013', '2014'],
         ),
         update="append"
         )
```
Thanks for your response!!
